# Generated by Django 5.0.6 on 2024-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6),
            preserve_default=False,
        ),
    ]
